In [1]:
input = sc.textFile("wasb:///iris-multiclass.csv")
input.count()

Starting Spark application

SparkContext available as 'sc'.
HiveContext available as 'sqlContext'.
150

In [2]:
input.first()

u'5.1,3.5,1.4,0.2,Iris-setosa'

In [3]:
splitter = input.map(lambda line: line.split(','))
num = splitter.map(lambda line: (line[4], 1)).reduceByKey(lambda a, b: a + b)
num.take(3)

[(u'Iris-virginica', 50), (u'Iris-setosa', 50), (u'Iris-versicolor', 50)]

In [4]:
from pyspark.sql.types import *
schemaString = "SepalLength SepalWidth PetalLength PetalWidth Species"
fields = [StructField(field_name, StringType(), True) for field_name in schemaString.split()]
schema = StructType(fields)
df = sqlContext.createDataFrame(splitter, schema)
df.groupBy("Species").count().show()

+---------------+-----+
|        Species|count|
+---------------+-----+
|    Iris-setosa|   50|
| Iris-virginica|   50|
|Iris-versicolor|   50|
+---------------+-----+

In [5]:
df.registerTempTable("iris")
sqlContext.sql("SELECT Species, COUNT(Species) FROM iris GROUP BY Species").show()

+---------------+---+
|        Species|_c1|
+---------------+---+
|    Iris-setosa| 50|
| Iris-virginica| 50|
|Iris-versicolor| 50|
+---------------+---+

In [6]:
from pyspark.sql.types import *
schemaString = "SepalLength SepalWidth PetalLength PetalWidth Species"
fields = [StructField(field_name, StringType(), True) for field_name in schemaString.split()]
schema = StructType(fields)
df = sqlContext.createDataFrame(splitter, schema)
df.groupBy("Species").count().show()

+---------------+-----+
|        Species|count|
+---------------+-----+
|    Iris-setosa|   50|
| Iris-virginica|   50|
|Iris-versicolor|   50|
+---------------+-----+

In [7]:
input = sc.textFile("wasb:///iris-multiclass.csv")
input.count()

150

In [8]:
input.first()

u'5.1,3.5,1.4,0.2,Iris-setosa'

In [9]:
splitter = input.map(lambda line: line.split(','))
num = splitter.map(lambda line: (line[4], 1)).reduceByKey(lambda a, b: a + b)
num.take(3)

[(u'Iris-virginica', 50), (u'Iris-setosa', 50), (u'Iris-versicolor', 50)]

In [10]:
from pyspark.sql.types import *
schemaString = "SepalLength SepalWidth PetalLength PetalWidth Species"
fields = [StructField(field_name, StringType(), True) for field_name in schemaString.split()]
schema = StructType(fields)
df = sqlContext.createDataFrame(splitter, schema)
df.groupBy("Species").count().show()

+---------------+-----+
|        Species|count|
+---------------+-----+
|    Iris-setosa|   50|
| Iris-virginica|   50|
|Iris-versicolor|   50|
+---------------+-----+

In [11]:
df.registerTempTable("iris")
sqlContext.sql("SELECT Species, COUNT(Species) FROM iris GROUP BY Species").show()

+---------------+---+
|        Species|_c1|
+---------------+---+
|    Iris-setosa| 50|
| Iris-virginica| 50|
|Iris-versicolor| 50|
+---------------+---+